export enum PageType {
    DOWNLOADS = "DOWNLOADS",
    FAQ = "FAQ",
    GLOSSARY = "GLOSSARY",
    PREVENTION = "PREVENTION",
    DV_FAIR = "DV_FAIR",
    NAVIGATOR = "NAVIGATOR",
    LEADERSHIP = "LEADERSHIP",
    PRIVACY_POLICY= "PRIVACY_POLICY"
}